apiVersion: v1
kind: ConfigMap
metadata:
  name: pablofm-p1-pro-values
  namespace: numinia
  annotations:
    config-version: "1.0.0"
data:
  values.yaml: |
    awsSecretName: "hyperfy2-numinia-pablofm-p1-pro"
    orgName: "numinia"
    appName: "pablofm-p1"
    environment: "pro"
    namespace: numinia
    serviceAccountName: "numinia"
    image:
      repository: "ghcr.io/numengames/numinia-hyperfy2"
      tag: "dev"
    world: "pro-pablofm-p1"
    publicMaxUploadSize: "1"
    publicWsUrl: "wss://pablofm-p1.numinia.xyz/ws"
    publicApiUrl: "https://pablofm-p1.numinia.xyz/api"
    assetsBaseUrl: "https://statics.numinia.xyz/hyperfy-spaces/numinia/pablofm-p1/latest/assets"
    clean: "true"
    tlsSecretName: "numinia-tls"
    resources:
      requests:
        cpu: "256m"
        memory: "256Mi"
      limits:
        cpu: "1024m"
        memory: "2048Mi"
    autoscaling:
      minScale: 0
      maxScale: 1
    domainMapping:
      enabled: true
      hostname: pablofm-p1.numinia.xyz
      namespace: numinia
