apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: knative-operator
      version: "v1.17.7" # match the operator version captured from the cluster
      sourceRef:
        kind: HelmRepository
        name: knative-operator
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
