apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: numinia
resources:
  - ../org-config/overlays/pro
  - ../city-of-mesa/pro
  - ../house-of-riddles/pro
  - ../lemuria-academy/pro
  - ../multiplex/pro
  - ../test-1/pro